name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Run Spotless check
      run: ./gradlew spotlessCheck

    - name: Run tests
      run: ./gradlew test

    - name: Build executable jar
      run: ./gradlew jar

    - name: Upload jar artifact
      uses: actions/upload-artifact@v4
      with:
        name: trash-api-jar
        path: app/build/libs/*.jar
